# Generated by Django 2.2.6 on 2019-10-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfact', '0002_auto_20191028_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(max_length=100),
        ),
    ]
