# Generated by Django 2.2.6 on 2019-10-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfact', '0004_auto_20191028_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_image_recto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_image_verso',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_op',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
