# Generated by Django 2.2.6 on 2019-10-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfact', '0005_auto_20191028_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
