# Generated by Django 2.2.6 on 2019-11-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfact', '0008_profil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='save',
            new_name='saves',
        ),
    ]
