nguage: python
python:
  - '3.7'

branches:
  only:
    - master

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings"

services:
  - postgresql

script:
  - ./manage.py test
